server:
  port: 8090
# keystore
  ssl:
    key-store: keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: boardAPI      
spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: tester
    password: password
  # auto build
  devtools:
    livereload.enabled: true    

